name: 🐛 Bug Report
description: File a bug report for react-native-nitro-screen-recorder
title: "🐛 "
labels: [🐛 bug]
body:
  - type: textarea
    attributes:
      label: What's happening?
      description: Describe what you’re trying to do, what you expected, and what actually happened. Include any visible errors or misbehavior.
      placeholder: |
        I started a global recording, but when I call stopGlobalRecording the file is undefined and no error is thrown.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Environment
      description: Check all that apply
      options:
        - label: I'm using Expo
        - label: I'm on the New Architecture
        - label: I installed `react-native-nitro-modules`
        - label: I build with EAS
        - label: I build locally
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Platform(s)
      options:
        - iOS
        - Android
        - Both
      description: Select the platform(s) where the issue occurs.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Exact steps to reproduce the bug (include any configuration, permissions, or setup steps).
      placeholder: |
        1. Start global recording with startGlobalRecording({ enableMic: true })
        2. Wait 5 seconds
        3. Call stopGlobalRecording({ settledTimeMs: 500 })
        4. Observe undefined file output
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproducible Code
      description: Paste a minimal code snippet that reproduces the issue. It will be formatted automatically.
      render: tsx
      placeholder: |
        const { isRecording } = useGlobalRecording({
          onRecordingFinished: (file) => console.log('got file', file),
        });
        startGlobalRecording({ enableMic: true });
    validations:
      required: false

  - type: textarea
    attributes:
      label: package.json
      description: Paste the relevant portion (dependencies and scripts) of your package.json.
      placeholder: |
        {
          "dependencies": {
            "react-native-nitro-screen-recorder": "0.3.2",
            "expo": "54.0.0",
            "react-native": "0.76.9"
          }
        }
    validations:
      required: false

  - type: textarea
    attributes:
      label: app.json
      description: Paste your Expo `app.json` configuration (omit secrets).
      placeholder: |
        {
          "expo": {
            "plugins": ["react-native-nitro-screen-recorder"]
          }
        }
    validations:
      required: false

  - type: textarea
    attributes:
      label: app.config.ts
      description: Paste your `app.config.ts` (omit secrets and API keys).
      placeholder: |
        export default {
          expo: {
            name: "MyApp",
            plugins: [["react-native-nitro-screen-recorder", {}]],
          },
        };
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error / Build Logs
      description: Paste relevant terminal, Metro, or Xcode/Gradle logs.
      placeholder: |
        ❌  (ios/ScreenRecorder/BroadcastWriter.swift:11:33)
        unknown attribute 'retroactive'
    validations:
      required: false

  - type: textarea
    attributes:
      label: Reproduction Project (Optional)
      description: Paste a link to a minimal reproducible repository or Snack.
      placeholder: https://github.com/yourname/repro-repo
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Confirmation
      options:
        - label: I have followed the [Troubleshooting Guide](https://github.com/margelo/react-native-nitro-screen-recorder/blob/main/docs/troubleshooting.md)
        - label: I agree to follow this project's [Code of Conduct](https://github.com/margelo/react-native-nitro-screen-recorder/blob/main/CODE_OF_CONDUCT.md)
        - label: I searched for similar issues and found none
          required: true
